### ISSUE TITLE
Needs Updates - Errors when including without mjml & body tags

### ISSUE THREAD

**Issue by CyberPunkCodes** [mjmlio/atom-linter-mjml#11]
As one person already said in #9 , this needs updated to the latest MJML version.

This also is throwing errors on a project I created with the latest MJML app.

My main template includes other template files, such as header.

```
<mjml>
  <mj-head>
  </mj-head>
  <mj-body>
    <mj-include path="./header.mjml" />
    <mj-include path="./content.mjml" />
    <mj-include path="./footer.mjml" />
  </mj-body>
</mjml>
```

And the included file example for say `header.mjml`:

```
<mj-section>
  <mj-column>
    <mj-text>
      The Header Here
    </mj-text>
  </mj-column>
</mj-section>
```

Throws a linter error complaining about missing the `<mjml>` and `<mj-body>` tags.

**Comment by iRyusa** [comment]
Well, we did that in the past, but it was a messy move from us. 

Now in MJML4, we can validate included files and show errors where you includes it, so the context of include can throw errors / or not depending of how you're using it.

But as #9 said, we should update this package to MJML4 now 👍
