### ISSUE TITLE
Linter finds error properly but always says the error is in the last line of the code

### ISSUE THREAD

**Issue by gdavalos** [mjmlio/atom-linter-mjml#4]
I think the title is pretty self-explanatory, when I use the linter and it finds any errors in the code they're shown as if they were in the last line of the code (this happens with any error and any number of errors)
![error mjml](https://cloud.githubusercontent.com/assets/15005675/22808720/15064f84-eef3-11e6-890a-cf6973f1c604.PNG)

**Comment by iRyusa** [comment]
Hi @gdavalos  and thanks for reporting this,

It should be fix in next MJML release, i'll keep this updated

**Comment by ngarnier** [comment]
Hello, I'm closing as this is fixed in the v1.1.0 of the plugin. Thanks for reporting!
