### ISSUE TITLE
<mj-include> doesn't exist... 

### ISSUE THREAD

**Issue by gustavringblom** [mjmlio/atom-linter-mjml#6]
`<mj-include>` doesn't exist. Please add this to the linter-mjml package.

Thanks!

**Comment by iRyusa** [comment]
Hi @gustavringblom 

There is already an issue on MJML repo : https://github.com/mjmlio/mjml/issues/651

I don't know if we can do anything about it yet, i'm closing this issue for now but feel free to check the other issue for updates
